# Generated by Django 4.2.9 on 2024-01-23 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Boooking',
            new_name='Booking',
        ),
    ]
